### ISSUE TITLE
[BUG] cannot use __orchestrion_instrument.WrapHandlerFunc

### ISSUE THREAD

**Issue by tonyredondo** [DataDog/orchestrion#400]
**Version of orchestrion**

0.9.4

**Describe what happened:**

Received this build error:

```
config/service/http_health_forwarder.go:157: cannot use __orchestrion_instrument.WrapHandlerFunc(func(w http.ResponseWriter, r *http.Request) {…}) (value of type "net/http".HandlerFunc) as handlerFunc value in return statement
```

function:
```go

func healthCheckBuilder(serviceName string, healthClient *httpHealthClient) handlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// ...
	}
}

```

**Describe what you expected:**

A normal build execution

**Steps to reproduce the issue:**

**Additional environment details (Version of Go, Operating System, etc.):**

**Comment by rarguelloF** [comment]
@tonyredondo Thanks for reporting the issue!

Could you please share the `handlerFunc` type? To make sure I accurately reproduce the issue.

**Comment by tonyredondo** [comment]
> [@tonyredondo](https://github.com/tonyredondo) Thanks for reporting the issue!
> 
> Could you please share the `handlerFunc` type? To make sure I accurately reproduce the issue.

shared offline.
