### ISSUE TITLE
[BUG]  Grpc interceptor strategy does not work if there is an existing interceptor

### ISSUE THREAD

**Issue by cvolante54** [DataDog/orchestrion#416]
In Golang, you can only call grpc.UnaryInterceptor once, given that the orchestrion adds it's own interceptor, if the user had their own interceptor the code will fail with 

```
panic: The unary server interceptor was already set and may not be reset.

goroutine 1 [running]:
main.main.UnaryInterceptor.func14(0x10c0e7f01?)
        /Users/cvolantesilva/go/pkg/mod/google.golang.org/grpc@v1.68.0/server.go:439 +0x4f
google.golang.org/grpc.(*funcServerOption).apply(0x8?, 0x8?)
        /Users/cvolantesilva/go/pkg/mod/google.golang.org/grpc@v1.68.0/server.go:212 +0x19
google.golang.org/grpc.NewServer({0xc000799e98, 0x3, 0x10c8dbde2?})
        /Users/cvolantesilva/go/pkg/mod/google.golang.org/grpc@v1.68.0/server.go:661 +0x117
```

**Version of orchestrion**
0.9.4

**Describe what happened:**
Application fails to start

**Describe what you expected:**
Application starts

**Steps to reproduce the issue:**
Add custom interceptors in the code, ex:

`gs = grpc.NewServer(
			grpc.UnaryInterceptor(...))`

**Additional environment details (Version of Go, Operating System, etc.):**

**Comment by RomainMuller** [comment]
Thanks for reporting this!

This is indeed annoying... That might be a limitation of the current implementation of gRPC tracing in `dd-trace-go`, but we might be able to find a proper way to compose interceptors instead, ro something...

Crashing the app at start-up is obviously not the desired behavior...
