### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by felixge** [DataDog/orchestrion#427]
**Version of orchestrion**

orchestrion v1.0.0-rc.1

**Describe what happened:**

Followed [docs](https://docs.datadoghq.com/fr/tracing/trace_collection/automatic_instrumentation/dd_libraries/go/?tab=compiletimeinstrumentation) for trying orchestrion with: https://github.com/ybkuroki/go-webapp-sample

**Describe what you expected:**

No errors. But actually got the following error when following the git commit step:

```
$ git commit -m "chore: enable orchestrion" go.mod go.sum orchestrion.tool.go
error: pathspec 'orchestrion.tool.go' did not match any file(s) known to git
```

Note: The file `orchestrion.tool.go` exists in my local dir, but since there is no `git add` step or similar, git commit is confused. So this workaround allows me to proceed:

```
$ git add orchestrion.tool.go
```

**Steps to reproduce the issue:**

Checkout a new Go repo, and follow the steps below.

```
go install github.com/DataDog/orchestrion@latest
orchestrion pin
git commit -m "chore: enable orchestrion" go.mod go.sum orchestrion.tool.go
```

**Additional environment details (Version of Go, Operating System, etc.):**

macOS

**Comment by RomainMuller** [comment]
This will be fixed by https://github.com/DataDog/documentation/pull/26495
