### ISSUE TITLE
Support for instrumenting Fiber (gofiber/fiber)

### ISSUE THREAD

**Issue by dserodio** [DataDog/orchestrion#44]
Our team utilizes the Fiber framework (https://github.com/gofiber/fiber) for developing web apps. It would be awesome if Orchestrion could support it.

**Comment by lwalther-ddog** [comment]
I work in datadog as a Sales engineer and I am testing the feature for a customer. COuld you please allow me to try it.

**Comment by dserodio** [comment]
> I work in datadog as a Sales engineer and I am testing the feature for a customer. COuld you please allow me to try it.

Sorry, I don't understand. I'm asking for someone to implement this, I have not implemented it (my knowledge of Go is too basic for this) 😊
