### ISSUE TITLE
[BUG] import with dot fails

### ISSUE THREAD

**Issue by rwong2888** [DataDog/orchestrion#50]
**Describe what happened:**

got an error like below

> Failed to scan: error scanning file <file.go>: error decorating file <file.go>: <package> unsupported dot-import found for [github.com/foo](http://github.com/foo)

**Describe what you expected:**

expected orchestrion to handle inserts, etc, however it failed on imports with dots. i had to rename the dot to bypass it, and then revert the rename. it would be good if dot would not break orchestrion

**Steps to reproduce the issue:**

import . github.com/foo

**Comment by RomainMuller** [comment]
We have now released `orchestrion@v0.7.1` which ought to address this issue, and has a new mode of operation. I'll close this issue now, but I encourage you to try it & let us know if you encounter any issues!
